"""
TrackMan Pitching Report — Streamlit App
==========================================
Install:   pip install streamlit pandas numpy matplotlib scipy pyarrow
Run with:  streamlit run trackman_app.py

Flow:
  1. fetch_data.py runs daily and writes data/pitches.parquet
  2. This app reads that file — zero API calls
  3. Pick team -> pick pitcher(s) -> Generate report
  4. Preview in browser + PDF download button

Requires: D1_percentiles.json in same folder (for color grading)
          data/pitches.parquet (generated by fetch_data.py)
"""

import streamlit as st
import json, os, io, math, warnings, requests
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle, Polygon
from matplotlib.backends.backend_pdf import PdfPages
from matplotlib.gridspec import GridSpec
from matplotlib.colors import LinearSegmentedColormap
from scipy.stats import gaussian_kde
from datetime import date, timedelta, datetime
warnings.filterwarnings("ignore")





# ===========================================================================
# PAGE CONFIG
# ===========================================================================
st.set_page_config(page_title="TrackMan Pitching Report", layout="wide", page_icon="⚾")

# ===========================================================================
# CONSTANTS
# ===========================================================================
STRIKE_CALLS = {"StrikeCalled", "StrikeSwinging", "FoulBallNotFieldable", "InPlay"}
SWING_CALLS  = {"StrikeSwinging", "FoulBallNotFieldable", "InPlay"}
PITCH_COLORS = {
    "Fastball": "#D32F2F", "FourSeamFastBall": "#D32F2F",
    "Sinker": "#E65100", "TwoSeamFastBall": "#E65100",
    "Cutter": "#B8A000", "Slider": "#00897B", "Curveball": "#1565C0",
    "ChangeUp": "#F9A825", "Changeup": "#F9A825",
    "Splitter": "#00796B", "Sweeper": "#7B1FA2", "Other": "#888888",
}
BG_COLOR = "#FFFFFF"
PANEL_COLOR = "#F7F8FA"
GRID_COLOR = "#D5D8DC"
TEXT_COLOR = "#1A1A2E"
ACCENT_COLOR = "#1565C0"
MUTED_TEXT = "#6B7280"
AUTO_CORRECT_PITCHES = True
MIN_CLUSTER_SIZE = 3

# ===========================================================================
# D1 PERCENTILE COLOR GRADING
# ===========================================================================
GRADE_CMAP = LinearSegmentedColormap.from_list("grade", [
    (0.0, "#4575B4"), (0.25, "#91BFDB"), (0.5, "#FFFFFF"),
    (0.75, "#FDB863"), (1.0, "#E66101"),
])

@st.cache_data(ttl=3600)
def load_percentiles():
    paths = [
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "D1_percentiles.json"),
        os.path.join(os.path.expanduser("~"), "Downloads", "D1_percentiles.json"),
        "D1_percentiles.json",
    ]
    for p in paths:
        if os.path.exists(p):
            with open(p) as f:
                return json.load(f)
    return {}

D1_PCTLS = load_percentiles()

def get_percentile(pitch_type, stat_name, value):
    if not D1_PCTLS: return None
    pt_map = {"FourSeamFastBall": "Fastball", "TwoSeamFastBall": "Sinker", "Changeup": "ChangeUp"}
    pt = pt_map.get(pitch_type, pitch_type)
    pt_data = D1_PCTLS.get(pt, {}).get(stat_name, {})
    pctls = pt_data.get("percentiles", {})
    if not pctls: return None
    pts_list = sorted([(int(k), v) for k, v in pctls.items()], key=lambda x: x[0])
    if value <= pts_list[0][1]: return pts_list[0][0]
    if value >= pts_list[-1][1]: return pts_list[-1][0]
    for i in range(len(pts_list) - 1):
        p0, v0 = pts_list[i]; p1, v1 = pts_list[i + 1]
        if v0 <= value <= v1:
            if v1 == v0: return (p0 + p1) / 2
            return p0 + (value - v0) / (v1 - v0) * (p1 - p0)
        elif v0 >= value >= v1:
            if v0 == v1: return (p0 + p1) / 2
            return p0 + (v0 - value) / (v0 - v1) * (p1 - p0)
    return None

def grade_color(pitch_type, stat_name, value, higher_is_better=True):
    pctile = get_percentile(pitch_type, stat_name, value)
    if pctile is None: return None
    norm = pctile / 100.0
    if not higher_is_better: norm = 1.0 - norm
    return GRADE_CMAP(norm)

# ===========================================================================
# UTILITY FUNCTIONS
# ===========================================================================
def pc(pt): return PITCH_COLORS.get(pt, "#C8C8C8")

def sg(d, *keys, default=None):
    for k in keys:
        if isinstance(d, dict): d = d.get(k, default)
        else: return default
    return d

def sf(v):
    if v is None: return np.nan
    try: return float(v)
    except: return np.nan

def resolve_pt(row):
    t = row.get("TaggedPitchType", ""); a = row.get("AutoPitchType", "")
    if t and t not in ("", "Undefined"): return t
    if a and a not in ("", "Undefined"): return a
    return "Other"

def calc_xwoba(ev, la):
    if pd.isna(ev) or pd.isna(la): return np.nan
    if ev < 50: return 0.05
    if la > 60: return 0.05
    if la > 50: return 0.05 + max(0, (ev - 90)) * 0.01
    if la < -10: return 0.05
    if la < 10:
        if ev >= 100: return 0.50
        if ev >= 90: return 0.30
        if ev >= 80: return 0.20
        return 0.10
    if ev >= 105: base = 1.8
    elif ev >= 100: base = 1.4
    elif ev >= 95: base = 0.9
    elif ev >= 90: base = 0.55
    elif ev >= 85: base = 0.35
    elif ev >= 80: base = 0.25
    elif ev >= 70: base = 0.15
    else: base = 0.08
    la_opt = 24.0
    la_penalty = ((la - la_opt) / 20.0) ** 2
    modifier = max(0.3, 1.0 - la_penalty * 0.5)
    return min(base * modifier, 2.1)

def calc_ip(pd_):
    total = 0
    for (_, _), grp in pd_.groupby(["Inning", "PAofInning"]):
        last = grp.loc[grp["PitchNo"].idxmax()]
        oop = last["OutsOnPlay"]
        korbb = last.get("KorBB", "")
        result = last.get("PlayResult", "")
        if pd.notna(oop) and oop > 0:
            total += int(oop)
        elif korbb == "Strikeout":
            reached = result in ("Single", "Double", "Triple", "HomeRun",
                                 "Error", "FieldersChoice", "CaughtStealing",
                                 "ReachedOnError")
            if not reached:
                total += 1
    return f"{total // 3}.{total % 3}"

def calc_pa(pd_): return pd_.groupby(["Inning", "PAofInning"]).ngroups

def calc_er(pd_):
    total = 0
    for (_, _), grp in pd_.groupby(["Inning", "PAofInning"]):
        last = grp.loc[grp["PitchNo"].idxmax()]
        rs = last["RunsScored"]
        if pd.notna(rs) and rs > 0:
            total += int(rs)
        elif last["PlayResult"] == "HomeRun":
            total += 1
    return total

def in_zone(s):
    return (s["PlateLocSide"].notna() & s["PlateLocHeight"].notna() &
            (s["PlateLocSide"].abs() <= 0.95) &
            (s["PlateLocHeight"] >= 1.6) & (s["PlateLocHeight"] <= 3.5))

def auto_correct_pitch_types(pitcher_df):
    if not AUTO_CORRECT_PITCHES: return pitcher_df, 0
    df = pitcher_df.copy(); corrections = 0
    features = ["RelSpeed", "InducedVertBreak", "HorzBreak"]
    for pname in df["Pitcher"].unique():
        pmask = df["Pitcher"] == pname; pdf = df[pmask].copy()
        valid = pdf[features].notna().all(axis=1)
        if valid.sum() < 5: continue
        centroids, stds = {}, {}
        for pt in pdf.loc[valid, "PitchType"].unique():
            if pt in ("Other", "Undefined", ""): continue
            ptmask = (pdf["PitchType"] == pt) & valid
            if ptmask.sum() >= MIN_CLUSTER_SIZE:
                centroids[pt] = pdf.loc[ptmask, features].mean().values
                stds[pt] = pdf.loc[ptmask, features].std().values
                stds[pt] = np.where(stds[pt] < 0.5, 2.0, stds[pt])
        if len(centroids) < 2: continue
        for idx in pdf[valid].index:
            row_vals = pdf.loc[idx, features].values.astype(float)
            tagged = pdf.loc[idx, "PitchType"]
            if tagged not in centroids: continue
            own_max_sd = (np.abs(row_vals - centroids[tagged]) / stds[tagged]).max()
            if own_max_sd > 2.5:
                best_type, best_dist = tagged, own_max_sd
                for other_pt, other_cent in centroids.items():
                    if other_pt == tagged: continue
                    other_max_sd = (np.abs(row_vals - other_cent) / stds[other_pt]).max()
                    if other_max_sd < best_dist and other_max_sd < 1.5:
                        best_dist = other_max_sd; best_type = other_pt
                if best_type != tagged:
                    df.loc[idx, "PitchType"] = best_type; corrections += 1
    return df, corrections

def fmt(s, fn="mean", d=1):
    v = s.dropna()
    if v.empty: return "—"
    r = v.mean() if fn == "mean" else v.max()
    return f"{r:.{d}f}"

# ===========================================================================
# DRAWING FUNCTIONS
# ===========================================================================
def draw_zone(ax, data, title, pts):
    ax.set_facecolor(PANEL_COLOR)
    ax.add_patch(Rectangle((-0.95, 1.6), 1.9, 1.9, fill=False, ec="#333333", lw=1.5, alpha=0.8, zorder=3))
    ax.add_patch(Rectangle((-0.95, 1.6), 1.9, 1.9, fill=True, fc="#E8EDF2", alpha=0.3, zorder=2))
    ax.add_patch(Rectangle((-1.4, 1.2), 2.8, 2.7, fill=False, ec="#AAAAAA", lw=0.7, ls="--", alpha=0.4, zorder=2))
    ax.add_patch(Polygon([(-.708, .15), (.708, .15), (.708, .35), (0, .55), (-.708, .35)],
                         closed=True, fc="none", ec=MUTED_TEXT, lw=.7, alpha=0.4))
    outcome_markers = {
        "BallCalled": ("o", False), "BallinDirt": ("o", False), "BallIntentional": ("o", False),
        "StrikeCalled": ("o", True), "StrikeSwinging": ("X", True),
        "FoulBallNotFieldable": ("^", True), "FoulBallFieldable": ("^", True),
        "InPlay": ("s", True), "HitByPitch": ("D", True),
    }
    for pt in pts:
        s = data[data["PitchType"] == pt]
        if s.empty: continue
        color = pc(pt)
        for call, grp in s.groupby("PitchCall"):
            marker, filled = outcome_markers.get(call, ("o", False))
            x = grp["PlateLocSide"]; y = grp["PlateLocHeight"]
            valid = x.notna() & y.notna()
            if not valid.any(): continue
            if filled:
                ax.scatter(x[valid], y[valid], marker=marker, c=color, s=45, alpha=0.9,
                           edgecolors="black", linewidths=0.3, zorder=5)
            else:
                ax.scatter(x[valid], y[valid], marker=marker, c="none", s=45, alpha=0.9,
                           edgecolors=color, linewidths=1.2, zorder=5)
    ax.set_xlim(-2.5, 2.5); ax.set_ylim(0, 5); ax.set_aspect("equal")
    ax.set_title(title, fontsize=9, fontweight="bold", color=TEXT_COLOR, pad=6)
    ax.set_xticks([]); ax.set_yticks([])
    for sp in ax.spines.values(): sp.set_visible(False)

def draw_mov(ax, data, pts):
    ax.set_facecolor(PANEL_COLOR)
    ax.axhline(0, color=GRID_COLOR, ls="-", lw=1, zorder=1)
    ax.axvline(0, color=GRID_COLOR, ls="-", lw=1, zorder=1)
    for r in [5, 10, 15, 20]:
        ax.add_patch(plt.Circle((0, 0), r, fill=False, ec=GRID_COLOR, lw=0.3, ls="--", alpha=0.3))
    for pt in pts:
        s = data[data["PitchType"] == pt]
        if not s.empty:
            ax.scatter(s["HorzBreak"], s["InducedVertBreak"],
                       c=pc(pt), label=pt, s=40, alpha=.9, edgecolors="black", linewidths=0.3, zorder=5)
    ax.set_xlim(-25, 25); ax.set_ylim(-25, 25)
    ax.set_xlabel("HB (in)", fontsize=7, color=MUTED_TEXT)
    ax.set_ylabel("IVB (in)", fontsize=7, color=MUTED_TEXT)
    ax.set_title("Pitch Movement", fontsize=9, fontweight="bold", color=TEXT_COLOR, pad=6)
    ax.legend(loc="upper center", bbox_to_anchor=(.5, -.06), ncol=min(len(pts), 5),
              fontsize=6, frameon=False, labelcolor=TEXT_COLOR)
    ax.tick_params(labelsize=6, colors=MUTED_TEXT)
    for sp in ax.spines.values(): sp.set_color(GRID_COLOR)

def draw_release(ax, data, pts):
    ax.set_facecolor(PANEL_COLOR)
    all_rs = data["RelSide"].dropna(); all_rh = data["RelHeight"].dropna()
    for pt in pts:
        valid = data.loc[data["PitchType"] == pt, ["RelSide", "RelHeight"]].dropna()
        if not valid.empty:
            ax.scatter(valid["RelSide"].mean(), valid["RelHeight"].mean(),
                       c=pc(pt), s=80, alpha=0.95, edgecolors="black", linewidths=0.8, zorder=5)
    if not all_rs.empty and not all_rh.empty:
        avg_rs, avg_rh = all_rs.mean(), all_rh.mean()
        ax.axhline(avg_rh, color=ACCENT_COLOR, lw=1, alpha=0.5, zorder=3)
        ax.axvline(avg_rs, color=ACCENT_COLOR, lw=1, alpha=0.5, zorder=3)
        ax.text(avg_rs, avg_rh - 0.3, f"Avg ({avg_rs:.1f}, {avg_rh:.1f})",
                ha="center", va="top", fontsize=6, color=ACCENT_COLOR, family="monospace",
                fontweight="bold", bbox=dict(boxstyle="round,pad=0.2", fc=BG_COLOR,
                ec=ACCENT_COLOR, alpha=0.9, lw=0.5))
    ax.axvline(0, color=MUTED_TEXT, lw=0.5, ls="--", alpha=0.3)
    ax.set_xlabel("Release Side (ft)", fontsize=6, color=MUTED_TEXT)
    ax.set_ylabel("Release Height (ft)", fontsize=6, color=MUTED_TEXT)
    ax.set_title("Release Point", fontsize=9, fontweight="bold", color=TEXT_COLOR, pad=6)
    ax.tick_params(labelsize=6, colors=MUTED_TEXT)
    for sp in ax.spines.values(): sp.set_color(GRID_COLOR)
    if not all_rs.empty and not all_rh.empty:
        rs_c, rh_c = all_rs.mean(), all_rh.mean()
        pad = max(all_rs.std(), all_rh.std(), 0.3) * 4 + 0.3
        ax.set_xlim(rs_c - pad, rs_c + pad); ax.set_ylim(rh_c - pad, rh_c + pad)
    ax.set_aspect("equal")

# ===========================================================================
# DATA LOADING — reads from data/pitches.parquet (written by fetch_data.py)
# ===========================================================================
DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else os.getcwd(), "data")

@st.cache_data(ttl=300)
def load_all_pitches():
    """Load the full season parquet file. Cached for 5 minutes."""
    path = os.path.join(DATA_DIR, "pitches.parquet")
    if not os.path.exists(path):
        return None, None
    df = pd.read_parquet(path)
    # Parse GameDate
    df["GameDate"] = pd.to_datetime(df["GameDate"], errors="coerce").dt.date
    # Normalize pitch type names
    pt_normalize = {
        "FourSeamFastBall": "Fastball",
        "TwoSeamFastBall": "Sinker",
        "Changeup": "ChangeUp",
    }
    if "PitchType" in df.columns:
        df["PitchType"] = df["PitchType"].replace(pt_normalize)
    return df, path

def get_last_updated():
    ts_path = os.path.join(DATA_DIR, "last_updated.json")
    if not os.path.exists(ts_path):
        return None
    with open(ts_path) as f:
        return json.load(f).get("last_updated_date", "unknown")

def build_team_code_map(df):
    """Build a mapping from full team name (HomeTeam/AwayTeam) to PitcherTeam code."""
    mapping = {}
    for _, row in df[["HomeTeam", "AwayTeam", "PitcherTeam"]].dropna().iterrows():
        home = row["HomeTeam"]
        away = row["AwayTeam"]
        code = row["PitcherTeam"]
        # We can only map the pitcher's own team code
        # So we check both home/away against the code prefix
        code_prefix = code[:3].upper()
        for team in [home, away]:
            if team and team[:3].upper() == code_prefix:
                mapping[team] = code
    return mapping

def get_teams(df):
    teams = set()
    for col in ["HomeTeam", "AwayTeam"]:
        if col in df.columns:
            teams.update(df[col].dropna().unique())
    return sorted(t for t in teams if t)

def get_team_pitches(df, team_name, date_from, date_to):
    """Filter to pitches thrown by pitchers on the selected team in the date range."""
    # TopBottom == "Top" means away team is batting → home team is pitching
    # TopBottom == "Bottom" means home team is batting → away team is pitching
    # So: home team pitches when TopBottom == "Top"
    #     away team pitches when TopBottom == "Bottom"
    date_mask = (df["GameDate"] >= date_from) & (df["GameDate"] <= date_to)
    mask = date_mask & (
        ((df["HomeTeam"] == team_name) & (df["TopBottom"] == "Top")) |
        ((df["AwayTeam"] == team_name) & (df["TopBottom"] == "Bottom"))
    )
    return df[mask].copy()


def flatten_game(plays_raw, balls_raw):
    rows = []
    for p in plays_raw:
        rows.append({
            "PlayID": p.get("playID"),
            "PitchNo": sg(p, "taggerBehavior", "pitchNo"),
            "PAofInning": sg(p, "taggerBehavior", "pAofinning"),
            "PitchofPA": sg(p, "taggerBehavior", "pitchofPA"),
            "Pitcher": sg(p, "pitcher", "name", default=""),
            "PitcherTeam": sg(p, "pitcher", "team", default=""),
            "Batter": sg(p, "batter", "name", default=""),
            "BatterSide": sg(p, "batter", "side", default=""),
            "Inning": sg(p, "gameState", "inning"),
            "TopBottom": sg(p, "gameState", "topBottom"),
            "Outs": sg(p, "gameState", "outs"),
            "Balls": sg(p, "gameState", "balls"),
            "Strikes": sg(p, "gameState", "strikes"),
            "TaggedPitchType": sg(p, "pitchTag", "taggedPitchType", default=""),
            "PitchCall": sg(p, "pitchTag", "pitchCall", default=""),
            "AutoPitchType": sg(p, "pitchTag", "autoPitchType", default=""),
            "KorBB": p.get("korBB", ""),
            "PlayResult": sg(p, "playResult", "playResult", default=""),
            "OutsOnPlay": sf(sg(p, "playResult", "outsOnPlay", default=0)),
            "RunsScored": sf(sg(p, "playResult", "runsScored", default=0)),
        })
    plays_df = pd.DataFrame(rows)
    if plays_df.empty: return plays_df
    plays_df["PitchNo"] = pd.to_numeric(plays_df["PitchNo"], errors="coerce")
    plays_df = plays_df.sort_values("PitchNo").reset_index(drop=True)

    pr, hr_ = [], []
    for b in balls_raw:
        kind = b.get("kind", ""); pid = b.get("playId")
        if kind == "Pitch":
            pr.append({"PlayID": pid,
                "RelSpeed": sf(sg(b, "pitch", "release", "relSpeed")),
                "SpinRate": sf(sg(b, "pitch", "release", "spinRate")),
                "Extension": sf(sg(b, "pitch", "release", "extension")),
                "RelHeight": sf(sg(b, "pitch", "release", "relHeight")),
                "RelSide": sf(sg(b, "pitch", "release", "relSide")),
                "HorzBreak": sf(sg(b, "pitch", "movement", "horzBreak")),
                "InducedVertBreak": sf(sg(b, "pitch", "movement", "inducedVertBreak")),
                "PlateLocHeight": sf(sg(b, "pitch", "location", "plateLocHeight")),
                "PlateLocSide": sf(sg(b, "pitch", "location", "plateLocSide")),
                "VertApprAngle": sf(sg(b, "pitch", "location", "vertApprAngle")),
            })
        elif kind == "Hit":
            hr_.append({"PlayID": pid,
                "ExitSpeed": sf(sg(b, "hit", "launch", "exitSpeed")),
                "LaunchAngle": sf(sg(b, "hit", "launch", "angle")),
            })

    pbdf = pd.DataFrame(pr).drop_duplicates("PlayID", keep="first") if pr else pd.DataFrame()
    hbdf = pd.DataFrame(hr_).drop_duplicates("PlayID", keep="first") if hr_ else pd.DataFrame()

    df = plays_df
    if not pbdf.empty: df = df.merge(pbdf, on="PlayID", how="left")
    else:
        for c in ["RelSpeed","SpinRate","Extension","RelHeight","RelSide",
                   "HorzBreak","InducedVertBreak","PlateLocHeight","PlateLocSide","VertApprAngle"]:
            df[c] = np.nan
    if not hbdf.empty: df = df.merge(hbdf, on="PlayID", how="left")
    else:
        for c in ["ExitSpeed", "LaunchAngle"]: df[c] = np.nan
    df = df.drop_duplicates("PlayID", keep="first")
    return df

def identify_team_code(df, team_name, ht, at):
    if team_name.lower() in ht.lower():
        top_pitchers = df[df["TopBottom"] == "Top"]["PitcherTeam"].value_counts()
        if not top_pitchers.empty: return top_pitchers.index[0]
    elif team_name.lower() in at.lower():
        bot_pitchers = df[df["TopBottom"] == "Bottom"]["PitcherTeam"].value_counts()
        if not bot_pitchers.empty: return bot_pitchers.index[0]
    return None

# ===========================================================================
# GENERATE ONE PITCHER PAGE
# ===========================================================================
def generate_pitcher_page(p, pname, gdate, opp):
    N = len(p)
    if N == 0: return None

    ip = calc_ip(p); pa = calc_pa(p)
    hits = int(p["PlayResult"].isin(["Single", "Double", "Triple"]).sum())
    hr = int((p["PlayResult"] == "HomeRun").sum())
    k = int((p["KorBB"] == "Strikeout").sum())
    bb = int((p["KorBB"] == "Walk").sum())
    hbp = int((p["PitchCall"] == "HitByPitch").sum())
    spct = round(p["PitchCall"].isin(STRIKE_CALLS).sum() / N * 100, 1)

    wh = p["PitchCall"] == "StrikeSwinging"
    sw = p["PitchCall"].isin(SWING_CALLS)
    iz = p["InZone"]
    ooz = ~iz

    zpct = round(iz.sum() / N * 100, 1)
    wpct = round(wh.sum() / sw.sum() * 100, 1) if sw.sum() else 0
    cpct = round((sw & ooz).sum() / ooz.sum() * 100, 1) if ooz.sum() else 0
    iz_sw = (sw & iz).sum()
    iz_wh_ct = (wh & iz).sum()
    izwp = round(iz_wh_ct / iz_sw * 100, 1) if iz_sw else 0

    pts = p["PitchType"].value_counts().index.tolist()

    fig = plt.figure(figsize=(20, 12), facecolor=BG_COLOR)
    gs = GridSpec(4, 4, figure=fig,
                  height_ratios=[.06, .02, .42, .50],
                  width_ratios=[1, 1, 1, 0.65],
                  hspace=.18, wspace=.18,
                  top=0.96, bottom=0.02, left=0.03, right=0.97)

    ax = fig.add_subplot(gs[0, :]); ax.set_facecolor(BG_COLOR); ax.axis("off")
    ax.text(.5, .78, pname.upper(), ha="center", va="center", fontsize=28,
            fontweight="bold", color=TEXT_COLOR, family="monospace")
    ax.text(.5, .22, f"{gdate:%B %d, %Y}   ·   vs {opp}",
            ha="center", va="center", fontsize=14, color=ACCENT_COLOR, family="monospace")

    ax = fig.add_subplot(gs[1, :]); ax.set_facecolor(BG_COLOR); ax.axis("off")
    stats_str = (f"IP {ip}   ·   PA {pa}   ·   P {N}   ·   "
                 f"H {hits + hr}   ·   K {k}   ·   BB {bb}   ·   HBP {hbp}   ·   HR {hr}   ·   "
                 f"STR% {spct}%")
    ax.text(.5, .65, stats_str, ha="center", va="center", fontsize=11,
            color=TEXT_COLOR, family="monospace", fontweight="bold")
    legend_str = "○ Ball    ● Called Strike    ✕ Swinging Strike    ▲ Foul    ■ In Play"
    ax.text(.5, .05, legend_str, ha="center", va="center", fontsize=9,
            color=TEXT_COLOR, family="monospace")

    lhb = p[p["BatterSide"] == "Left"]
    ax_l = fig.add_subplot(gs[2, 0]); draw_zone(ax_l, lhb, f"vs LHB ({len(lhb)})", pts)
    rhb = p[p["BatterSide"] == "Right"]
    ax_r = fig.add_subplot(gs[2, 1]); draw_zone(ax_r, rhb, f"vs RHB ({len(rhb)})", pts)
    ax_m = fig.add_subplot(gs[2, 2]); draw_mov(ax_m, p, pts)
    ax_rp = fig.add_subplot(gs[2, 3]); draw_release(ax_rp, p, pts)

    ax_t = fig.add_subplot(gs[3, :]); ax_t.set_facecolor(BG_COLOR); ax_t.axis("off")
    trows = []
    grade_cells = {}
    for ri, pt in enumerate(pts):
        s = p[p["PitchType"] == pt]; n = len(s)
        s_iz = in_zone(s); _sw = s["PitchCall"].isin(SWING_CALLS)
        _wh = s["PitchCall"] == "StrikeSwinging"
        _ooz = ~s_iz
        _ooz_sw = (_sw & _ooz).sum(); _ooz_n = _ooz.sum()
        _iz_sw = (_sw & s_iz).sum(); _iz_wh = (_wh & s_iz).sum()
        iz_whiff_str = f"{_iz_wh / _iz_sw * 100:.1f}%" if _iz_sw else "—"
        _sw_ct = _sw.sum()
        whiff_val = _wh.sum() / _sw_ct * 100 if _sw_ct else None
        whiff_str = f"{whiff_val:.1f}%" if whiff_val is not None else "—"
        chase_val = _ooz_sw / _ooz_n * 100 if _ooz_n else None
        chase_str = f"{chase_val:.1f}%" if chase_val is not None else "—"
        xw = s["xwOBA"].dropna()
        xwoba_val = xw.mean() if not xw.empty else None
        xwoba_str = f"{xwoba_val:.3f}" if xwoba_val is not None else "—"
        avg_velo_raw = s["RelSpeed"].dropna()
        avg_velo_val = avg_velo_raw.mean() if not avg_velo_raw.empty else None
        zone_val = s_iz.sum() / n * 100 if n else None
        zone_str = f"{zone_val:.1f}%" if zone_val is not None else "—"
        trows.append([pt, n, f"{n / N * 100:.1f}%",
                      fmt(s["RelSpeed"]), fmt(s["RelSpeed"], "max"),
                      fmt(s["SpinRate"], d=0),
                      fmt(s["InducedVertBreak"]), fmt(s["HorzBreak"]),
                      fmt(s["Extension"]), fmt(s["RelHeight"]), fmt(s["RelSide"]),
                      fmt(s["VertApprAngle"]),
                      xwoba_str, zone_str, whiff_str, chase_str, iz_whiff_str])

        data_row = ri + 1
        if avg_velo_val is not None:
            grade_cells[(data_row, 2)] = (pt, "velo", avg_velo_val, True)
        if xwoba_val is not None:
            grade_cells[(data_row, 11)] = (pt, "xwoba", xwoba_val, False)
        if zone_val is not None:
            grade_cells[(data_row, 12)] = (pt, "zone_pct", zone_val, True)
        if whiff_val is not None:
            grade_cells[(data_row, 13)] = (pt, "whiff_pct", whiff_val, True)
        if chase_val is not None:
            grade_cells[(data_row, 14)] = (pt, "chase_pct", chase_val, True)

    all_sw_ct = sw.sum()
    all_whiff = f"{wh.sum() / all_sw_ct * 100:.1f}%" if all_sw_ct else "0%"
    all_xw = p["xwOBA"].dropna()
    all_xwoba = f"{all_xw.mean():.3f}" if not all_xw.empty else "—"
    trows.append(["All", N, "100%", "—", "—", "—", "—", "—",
                  fmt(p["Extension"]), "—", "—", "—",
                  all_xwoba, f"{zpct}%", all_whiff, f"{cpct}%", f"{izwp}%"])

    cols = ["Count", "Usage%", "Avg\nVelo", "Max\nVelo", "Avg\nSpin",
            "IVB", "HB", "Ext", "RelH", "RelS", "VAA",
            "xwOBA", "Zone%", "Whiff%", "Chase%", "IZ\nWhiff%"]

    tbl = ax_t.table(cellText=[r[1:] for r in trows], rowLabels=[r[0] for r in trows],
                     colLabels=cols, loc="center", cellLoc="center")
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(9.5)
    tbl.scale(1, 2.2)

    for (row, col), cell in tbl.get_celld().items():
        cell.set_edgecolor(GRID_COLOR); cell.set_linewidth(0.6)
        if row == 0:
            cell.set_facecolor("#1E1E2E")
            cell.set_text_props(fontweight="bold", color="white", fontfamily="monospace", fontsize=9)
        elif col == -1:
            pitch_name = cell.get_text().get_text()
            if pitch_name == "All":
                cell.set_facecolor("#E8E8E8")
                cell.set_text_props(fontweight="bold", color=TEXT_COLOR, fontfamily="monospace", fontsize=10)
            else:
                cell.set_facecolor(pc(pitch_name))
                cell.set_text_props(fontweight="bold", color="white", fontfamily="monospace", fontsize=10)
        else:
            graded = False
            if (row, col) in grade_cells and row <= len(pts):
                pt_name, stat_name, raw_val, higher_better = grade_cells[(row, col)]
                gc = grade_color(pt_name, stat_name, raw_val, higher_better)
                if gc is not None:
                    cell.set_facecolor(gc)
                    cell.set_text_props(color=TEXT_COLOR, fontfamily="monospace", fontweight="bold", fontsize=9.5)
                    graded = True
            if not graded:
                if row == len(trows):
                    cell.set_facecolor("#E8E8E8")
                    cell.set_text_props(color=TEXT_COLOR, fontweight="bold", fontfamily="monospace", fontsize=9.5)
                elif row % 2 == 0:
                    cell.set_facecolor("#F4F6F9")
                    cell.set_text_props(color=TEXT_COLOR, fontfamily="monospace", fontsize=9.5)
                else:
                    cell.set_facecolor("#FFFFFF")
                    cell.set_text_props(color=TEXT_COLOR, fontfamily="monospace", fontsize=9.5)

    return fig

# ===========================================================================
# SEASON SUMMARY FUNCTIONS
# ===========================================================================
def calc_fip(k, bb, hbp_ct, hr_ct, ip_str):
    parts = ip_str.split(".")
    ip = int(parts[0]) + int(parts[1]) / 3 if len(parts) == 2 else float(ip_str)
    if ip == 0: return 0.0
    return (13 * hr_ct + 3 * (bb + hbp_ct) - 2 * k) / ip + 3.10

def generate_season_summary(pitcher_name, outings, date_from, date_to):
    all_dfs = []
    for p_df, gdate, opp in outings:
        df_copy = p_df.copy()
        df_copy["_game_date"] = gdate
        df_copy["_opp"] = opp
        all_dfs.append(df_copy)
    p = pd.concat(all_dfs, ignore_index=True)
    N = len(p)
    if N == 0: return None

    total_ip_outs = 0; total_k = 0; total_bb = 0
    total_hbp = 0; total_hr = 0; total_hits = 0; total_pa = 0
    for p_df, gdate, opp in outings:
        ip_s = calc_ip(p_df)
        parts = ip_s.split(".")
        total_ip_outs += int(parts[0]) * 3 + int(parts[1])
        total_k += int((p_df["KorBB"] == "Strikeout").sum())
        total_bb += int((p_df["KorBB"] == "Walk").sum())
        total_hbp += int((p_df["PitchCall"] == "HitByPitch").sum())
        total_hr += int((p_df["PlayResult"] == "HomeRun").sum())
        total_hits += int(p_df["PlayResult"].isin(["Single", "Double", "Triple"]).sum())
        total_pa += calc_pa(p_df)

    ip_full = total_ip_outs // 3; ip_rem = total_ip_outs % 3
    ip_str = f"{ip_full}.{ip_rem}"
    ip_float = ip_full + ip_rem / 3.0
    whip = ((total_bb + total_hits + total_hr) / ip_float) if ip_float > 0 else 0
    k_pct = (total_k / total_pa * 100) if total_pa > 0 else 0
    bb_pct = (total_bb / total_pa * 100) if total_pa > 0 else 0
    fip = calc_fip(total_k, total_bb, total_hbp, total_hr, ip_str)

    wh = p["PitchCall"] == "StrikeSwinging"
    sw = p["PitchCall"].isin(SWING_CALLS)
    iz = p["InZone"]; ooz = ~iz
    zpct = round(iz.sum() / N * 100, 1)
    wpct = round(wh.sum() / sw.sum() * 100, 1) if sw.sum() else 0
    cpct = round((sw & ooz).sum() / ooz.sum() * 100, 1) if ooz.sum() else 0
    iz_sw = (sw & iz).sum(); iz_wh_ct = (wh & iz).sum()
    izwp = round(iz_wh_ct / iz_sw * 100, 1) if iz_sw else 0
    pts = p["PitchType"].value_counts().index.tolist()

    fig = plt.figure(figsize=(20, 13), facecolor=BG_COLOR)
    gs = GridSpec(4, 3, figure=fig,
                  height_ratios=[.06, .04, .36, .54],
                  width_ratios=[1, 1.2, 1.2],
                  hspace=.22, wspace=.22,
                  top=0.96, bottom=0.02, left=0.04, right=0.97)

    ax = fig.add_subplot(gs[0, :]); ax.set_facecolor(BG_COLOR); ax.axis("off")
    ax.text(.5, .7, pitcher_name.upper(), ha="center", va="center", fontsize=28,
            fontweight="bold", color=TEXT_COLOR, family="monospace")
    ax.text(.5, .1, "Season Pitching Summary", ha="center", va="center",
            fontsize=14, color=ACCENT_COLOR, family="monospace")

    ax = fig.add_subplot(gs[1, :]); ax.set_facecolor(BG_COLOR); ax.axis("off")
    outing_details = []
    for p_df, gdate, opp in outings:
        o_ip = calc_ip(p_df)
        o_k = int((p_df["KorBB"] == "Strikeout").sum())
        o_bb = int((p_df["KorBB"] == "Walk").sum())
        outing_details.append(f"{gdate} vs {opp}: {o_ip}IP {o_k}K {o_bb}BB")

    banner = (f"IP {ip_str}   ·   FIP {fip:.2f}   ·   WHIP {whip:.2f}   ·   "
              f"K% {k_pct:.1f}%   ·   BB% {bb_pct:.1f}%   ·   K-BB% {k_pct - bb_pct:.1f}%   ·   "
              f"PA {total_pa}   ·   P {N}   ·   H {total_hits + total_hr}   ·   HR {total_hr}   ·   "
              f"K {total_k}   ·   BB {total_bb}   ·   {len(outings)} outing(s)")
    ax.text(.5, .7, banner, ha="center", va="center", fontsize=11, color=TEXT_COLOR, family="monospace", fontweight="bold")
    ax.text(.5, .2, f"{date_from} to {date_to}     |     " + "  /  ".join(outing_details),
            ha="center", va="center", fontsize=8.5, color=MUTED_TEXT, family="monospace")

    ax_velo = fig.add_subplot(gs[2, 0]); ax_velo.set_facecolor(PANEL_COLOR)
    pt_velo_sorted = sorted(pts, key=lambda x: p[p["PitchType"] == x]["RelSpeed"].median()
                            if not p[p["PitchType"] == x]["RelSpeed"].dropna().empty else 0, reverse=True)
    for i, pt in enumerate(pt_velo_sorted):
        velos = p.loc[p["PitchType"] == pt, "RelSpeed"].dropna()
        if len(velos) < 3: continue
        try:
            kde = gaussian_kde(velos, bw_method=0.3)
            x_range = np.linspace(velos.min() - 3, velos.max() + 3, 200)
            density = kde(x_range)
            density = density / density.max() * 0.38
            ax_velo.fill_betweenx(i + density, x_range, i - density, alpha=0.7, color=pc(pt))
            ax_velo.plot(x_range, i + density, color="black", lw=0.4)
            ax_velo.plot(x_range, i - density, color="black", lw=0.4)
            med = velos.median()
            ax_velo.plot([med, med], [i - 0.3, i + 0.3], color="black", lw=1, ls="--", alpha=0.5)
        except:
            pass
    ax_velo.set_yticks(range(len(pt_velo_sorted)))
    ax_velo.set_yticklabels(pt_velo_sorted, fontsize=9, fontfamily="monospace")
    ax_velo.set_xlabel("Velocity (mph)", fontsize=9, color=MUTED_TEXT)
    ax_velo.set_title("Velocity Distribution", fontsize=11, fontweight="bold", color=TEXT_COLOR, pad=6)
    ax_velo.tick_params(labelsize=6, colors=MUTED_TEXT)
    for sp in ax_velo.spines.values(): sp.set_color(GRID_COLOR)

    ax_mov = fig.add_subplot(gs[2, 1]); ax_mov.set_facecolor(PANEL_COLOR)
    ax_mov.axhline(0, color=GRID_COLOR, ls="-", lw=1, zorder=1)
    ax_mov.axvline(0, color=GRID_COLOR, ls="-", lw=1, zorder=1)
    for r in [5, 10, 15, 20]:
        ax_mov.add_patch(plt.Circle((0, 0), r, fill=False, ec=GRID_COLOR, lw=0.3, ls="--", alpha=0.3))
    for pt in pts:
        s = p[p["PitchType"] == pt]
        hb = s["HorzBreak"].dropna(); ivb = s["InducedVertBreak"].dropna()
        if not hb.empty and not ivb.empty:
            ax_mov.scatter(hb.mean(), ivb.mean(), c=pc(pt), label=pt, s=120, alpha=0.95,
                          edgecolors="black", linewidths=1, zorder=5, marker="o")
    ax_mov.set_xlim(-25, 25); ax_mov.set_ylim(-25, 25)
    ax_mov.set_xlabel("HB (in)", fontsize=9, color=MUTED_TEXT)
    ax_mov.set_ylabel("IVB (in)", fontsize=9, color=MUTED_TEXT)
    ax_mov.set_title("Avg Pitch Movement", fontsize=11, fontweight="bold", color=TEXT_COLOR, pad=6)
    ax_mov.legend(loc="upper center", bbox_to_anchor=(.5, -.06), ncol=min(len(pts), 5),
                  fontsize=9, frameon=False, labelcolor=TEXT_COLOR)
    ax_mov.tick_params(labelsize=6, colors=MUTED_TEXT)
    for sp in ax_mov.spines.values(): sp.set_color(GRID_COLOR)

    ax_usage = fig.add_subplot(gs[2, 2]); ax_usage.set_facecolor(PANEL_COLOR)
    lhb_data = p[p["BatterSide"] == "Left"]
    rhb_data = p[p["BatterSide"] == "Right"]
    lhb_total = len(lhb_data); rhb_total = len(rhb_data)
    bar_pts = sorted(pts, key=lambda x: p[p["PitchType"] == x]["RelSpeed"].median()
                     if not p[p["PitchType"] == x]["RelSpeed"].dropna().empty else 0, reverse=True)
    y_pos = np.arange(len(bar_pts)); bar_h = 0.35
    for i, pt in enumerate(bar_pts):
        lhb_pct = len(lhb_data[lhb_data["PitchType"] == pt]) / lhb_total * 100 if lhb_total > 0 else 0
        rhb_pct = len(rhb_data[rhb_data["PitchType"] == pt]) / rhb_total * 100 if rhb_total > 0 else 0
        ax_usage.barh(i + bar_h / 2, -lhb_pct, bar_h, color=pc(pt), alpha=0.8, edgecolor="black", lw=0.3)
        ax_usage.barh(i - bar_h / 2, rhb_pct, bar_h, color=pc(pt), alpha=0.8, edgecolor="black", lw=0.3)
        if lhb_pct > 2:
            ax_usage.text(-lhb_pct / 2, i + bar_h / 2, f"{lhb_pct:.1f}%", ha="center", va="center",
                         fontsize=6, fontweight="bold", color="white")
        if rhb_pct > 2:
            ax_usage.text(rhb_pct / 2, i - bar_h / 2, f"{rhb_pct:.1f}%", ha="center", va="center",
                         fontsize=6, fontweight="bold", color="white")
    ax_usage.set_yticks(y_pos)
    ax_usage.set_yticklabels(bar_pts, fontsize=9, fontfamily="monospace")
    ax_usage.axvline(0, color="black", lw=1)
    max_pct = max(60, max(
        [len(lhb_data[lhb_data["PitchType"] == pt]) / max(lhb_total, 1) * 100 for pt in bar_pts] +
        [len(rhb_data[rhb_data["PitchType"] == pt]) / max(rhb_total, 1) * 100 for pt in bar_pts]
    ) + 10)
    ax_usage.set_xlim(-max_pct, max_pct)
    ticks = ax_usage.get_xticks()
    ax_usage.set_xticklabels([f"{abs(t):.0f}%" for t in ticks], fontsize=6)
    ax_usage.set_title("Pitch Usage", fontsize=11, fontweight="bold", color=TEXT_COLOR, pad=6)
    ax_usage.text(-max_pct * 0.5, len(bar_pts) + 0.3, f"vs LHB ({lhb_total})", ha="center", fontsize=9,
                 color=MUTED_TEXT, fontweight="bold")
    ax_usage.text(max_pct * 0.5, len(bar_pts) + 0.3, f"vs RHB ({rhb_total})", ha="center", fontsize=9,
                 color=MUTED_TEXT, fontweight="bold")
    ax_usage.tick_params(labelsize=6, colors=MUTED_TEXT)
    for sp in ax_usage.spines.values(): sp.set_color(GRID_COLOR)

    ax_t = fig.add_subplot(gs[3, :]); ax_t.set_facecolor(BG_COLOR); ax_t.axis("off")
    trows = []
    grade_cells = {}
    for ri, pt in enumerate(pts):
        s = p[p["PitchType"] == pt]; n = len(s)
        s_iz = in_zone(s); _sw = s["PitchCall"].isin(SWING_CALLS)
        _wh = s["PitchCall"] == "StrikeSwinging"; _ooz = ~s_iz
        _ooz_sw = (_sw & _ooz).sum(); _ooz_n = _ooz.sum()
        _iz_sw = (_sw & s_iz).sum(); _iz_wh = (_wh & s_iz).sum()
        iz_whiff_str = f"{_iz_wh / _iz_sw * 100:.1f}%" if _iz_sw else "—"
        _sw_ct = _sw.sum()
        whiff_val = _wh.sum() / _sw_ct * 100 if _sw_ct else None
        whiff_str = f"{whiff_val:.1f}%" if whiff_val is not None else "—"
        chase_val = _ooz_sw / _ooz_n * 100 if _ooz_n else None
        chase_str = f"{chase_val:.1f}%" if chase_val is not None else "—"
        xw = s["xwOBA"].dropna()
        xwoba_val = xw.mean() if not xw.empty else None
        xwoba_str = f"{xwoba_val:.3f}" if xwoba_val is not None else "—"
        avg_velo_raw = s["RelSpeed"].dropna()
        avg_velo_val = avg_velo_raw.mean() if not avg_velo_raw.empty else None
        zone_val = s_iz.sum() / n * 100 if n else None
        zone_str = f"{zone_val:.1f}%" if zone_val is not None else "—"
        trows.append([pt, n, f"{n / N * 100:.1f}%",
                      fmt(s["RelSpeed"]), fmt(s["RelSpeed"], "max"),
                      fmt(s["SpinRate"], d=0),
                      fmt(s["InducedVertBreak"]), fmt(s["HorzBreak"]),
                      fmt(s["Extension"]), fmt(s["RelHeight"]), fmt(s["RelSide"]),
                      fmt(s["VertApprAngle"]),
                      xwoba_str, zone_str, whiff_str, chase_str, iz_whiff_str])

        data_row = ri + 1
        if avg_velo_val is not None:
            grade_cells[(data_row, 2)] = (pt, "velo", avg_velo_val, True)
        if xwoba_val is not None:
            grade_cells[(data_row, 11)] = (pt, "xwoba", xwoba_val, False)
        if zone_val is not None:
            grade_cells[(data_row, 12)] = (pt, "zone_pct", zone_val, True)
        if whiff_val is not None:
            grade_cells[(data_row, 13)] = (pt, "whiff_pct", whiff_val, True)
        if chase_val is not None:
            grade_cells[(data_row, 14)] = (pt, "chase_pct", chase_val, True)

    all_sw_ct = sw.sum()
    all_whiff = f"{wh.sum() / all_sw_ct * 100:.1f}%" if all_sw_ct else "0%"
    all_xw = p["xwOBA"].dropna()
    all_xwoba = f"{all_xw.mean():.3f}" if not all_xw.empty else "—"
    trows.append(["All", N, "100%", "—", "—", "—", "—", "—",
                  fmt(p["Extension"]), "—", "—", "—",
                  all_xwoba, f"{zpct}%", all_whiff, f"{cpct}%", f"{izwp}%"])

    cols = ["Count", "Usage%", "Avg\nVelo", "Max\nVelo", "Avg\nSpin",
            "IVB", "HB", "Ext", "RelH", "RelS", "VAA",
            "xwOBA", "Zone%", "Whiff%", "Chase%", "IZ\nWhiff%"]
    tbl = ax_t.table(cellText=[r[1:] for r in trows], rowLabels=[r[0] for r in trows],
                     colLabels=cols, loc="center", cellLoc="center")
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(9.5)
    tbl.scale(1, 2.2)

    for (row, col), cell in tbl.get_celld().items():
        cell.set_edgecolor(GRID_COLOR); cell.set_linewidth(0.6)
        if row == 0:
            cell.set_facecolor("#1E1E2E")
            cell.set_text_props(fontweight="bold", color="white", fontfamily="monospace", fontsize=9)
        elif col == -1:
            pitch_name = cell.get_text().get_text()
            if pitch_name == "All":
                cell.set_facecolor("#E8E8E8")
                cell.set_text_props(fontweight="bold", color=TEXT_COLOR, fontfamily="monospace", fontsize=10)
            else:
                cell.set_facecolor(pc(pitch_name))
                cell.set_text_props(fontweight="bold", color="white", fontfamily="monospace", fontsize=10)
        else:
            graded = False
            if (row, col) in grade_cells and row <= len(pts):
                pt_name, stat_name, raw_val, higher_better = grade_cells[(row, col)]
                gc = grade_color(pt_name, stat_name, raw_val, higher_better)
                if gc is not None:
                    cell.set_facecolor(gc)
                    cell.set_text_props(color=TEXT_COLOR, fontfamily="monospace", fontweight="bold")
                    graded = True
            if not graded:
                if row == len(trows):
                    cell.set_facecolor("#F0F0F0")
                    cell.set_text_props(color=TEXT_COLOR, fontweight="bold", fontfamily="monospace")
                elif row % 2 == 0:
                    cell.set_facecolor("#F7F8FA")
                    cell.set_text_props(color=TEXT_COLOR, fontfamily="monospace")
                else:
                    cell.set_facecolor("#FFFFFF")
                    cell.set_text_props(color=TEXT_COLOR, fontfamily="monospace")

    return fig

# ===========================================================================
# HEATMAP FUNCTIONS
# ===========================================================================
RUN_VALUES = {
    "StrikeSwinging": -0.065, "StrikeCalled": -0.038, "FoulBallNotFieldable": -0.025,
    "BallCalled": 0.032, "BallinDirt": 0.032, "BallIntentional": 0.032,
    "HitByPitch": 0.035,
}

def compute_pitch_run_value(row):
    call = row.get("PitchCall", "")
    if call in RUN_VALUES:
        return RUN_VALUES[call]
    if call == "InPlay":
        xw = row.get("xwOBA", np.nan)
        if pd.notna(xw):
            return (xw - 0.320) / 1.15
        return 0.0
    return 0.0

def generate_heatmap(p, pitch_type, metric="run_value"):
    sub = p[p["PitchType"] == pitch_type].copy()
    sub = sub[sub["PlateLocSide"].notna() & sub["PlateLocHeight"].notna()]
    if len(sub) < 5:
        return None

    is_density_only = False
    if metric == "location":
        is_density_only = True
        cmap_name = "YlOrRd"
        title_label = "Pitch Location Density"
        vmin, vmax = 0, 1
    elif metric == "run_value":
        sub["_val"] = sub.apply(compute_pitch_run_value, axis=1)
        cmap_name = "RdBu_r"
        title_label = "Run Value"
        vmin, vmax = -0.08, 0.08
    elif metric == "whiff":
        sub["_val"] = (sub["PitchCall"] == "StrikeSwinging").astype(float)
        cmap_name = "YlOrRd"
        title_label = "Whiff Rate"
        vmin, vmax = 0, 0.6
    elif metric == "xwoba":
        def xw_val(row):
            if row["PitchCall"] == "InPlay" and pd.notna(row.get("xwOBA")):
                return row["xwOBA"]
            elif row["PitchCall"] == "StrikeSwinging":
                return 0.0
            elif row["PitchCall"] == "StrikeCalled":
                return 0.05
            elif row["PitchCall"] in ("BallCalled", "BallinDirt"):
                return 0.4
            return np.nan
        sub["_val"] = sub.apply(xw_val, axis=1)
        sub = sub[sub["_val"].notna()]
        cmap_name = "RdYlBu_r"
        title_label = "xwOBA"
        vmin, vmax = 0, 0.8
    else:
        return None

    fig, axes = plt.subplots(1, 2, figsize=(12, 6), facecolor=BG_COLOR)

    for idx, (side, label) in enumerate([("Left", "vs LHB"), ("Right", "vs RHB")]):
        ax = axes[idx]
        ax.set_facecolor(PANEL_COLOR)
        side_data = sub[sub["BatterSide"] == side]

        ax.add_patch(Rectangle((-0.95, 1.6), 1.9, 1.9, fill=False, ec="black", lw=1.5, zorder=10))
        ax.add_patch(Polygon([(-.708, .15), (.708, .15), (.708, .35), (0, .55), (-.708, .35)],
                             closed=True, fc="#CCCCCC", ec="black", lw=.5, alpha=0.5, zorder=10))

        if len(side_data) >= 5:
            x = side_data["PlateLocSide"].values
            y = side_data["PlateLocHeight"].values
            xi = np.linspace(-2.5, 2.5, 80)
            yi = np.linspace(-0.5, 5.0, 80)
            Xi, Yi = np.meshgrid(xi, yi)
            try:
                positions = np.vstack([x, y])
                kde = gaussian_kde(positions, bw_method=0.4)
                density = kde(np.vstack([Xi.ravel(), Yi.ravel()])).reshape(Xi.shape)
                if is_density_only:
                    Zi = density / density.max() if density.max() > 0 else density
                    density_thresh = 0.05
                    Zi[Zi < density_thresh] = np.nan
                else:
                    vals = side_data["_val"].values
                    Zi = np.zeros_like(Xi)
                    for px, py, pv in zip(x, y, vals):
                        dist2 = (Xi - px) ** 2 + (Yi - py) ** 2
                        weights = np.exp(-dist2 / (2 * 0.3 ** 2))
                        Zi += weights * pv
                    weight_sum = np.zeros_like(Xi)
                    for px, py in zip(x, y):
                        dist2 = (Xi - px) ** 2 + (Yi - py) ** 2
                        weight_sum += np.exp(-dist2 / (2 * 0.3 ** 2))
                    weight_sum[weight_sum == 0] = 1
                    Zi = Zi / weight_sum
                    density_thresh = density.max() * 0.05
                    Zi[density < density_thresh] = np.nan
                im = ax.pcolormesh(Xi, Yi, Zi, cmap=cmap_name, vmin=vmin, vmax=vmax,
                                   shading="gouraud", zorder=1)
            except:
                pass
            ax.scatter(x, y, c="black", s=8, alpha=0.5, zorder=6)

        n_side = len(side_data)
        ax.set_title(f"{pitch_type} {label} ({n_side})", fontsize=11, fontweight="bold", color=TEXT_COLOR, pad=8)
        ax.set_xlim(-2.5, 2.5); ax.set_ylim(-0.5, 5.0)
        ax.set_xlabel("PlateLocSide", fontsize=8, color=MUTED_TEXT)
        if idx == 0:
            ax.set_ylabel("PlateLocHeight", fontsize=8, color=MUTED_TEXT)
        ax.tick_params(labelsize=7, colors=MUTED_TEXT)
        for sp in ax.spines.values(): sp.set_color(GRID_COLOR)

    fig.subplots_adjust(right=0.88)
    cbar_ax = fig.add_axes([0.90, 0.15, 0.02, 0.7])
    sm = plt.cm.ScalarMappable(cmap=cmap_name, norm=plt.Normalize(vmin=vmin, vmax=vmax))
    sm.set_array([])
    cbar = fig.colorbar(sm, cax=cbar_ax)
    cbar.set_label(title_label, fontsize=9)
    cbar.ax.tick_params(labelsize=7)
    fig.suptitle(f"{title_label} Heatmap — {pitch_type}", fontsize=14, fontweight="bold",
                 color=TEXT_COLOR, y=0.98)
    return fig

# ===========================================================================
# HELPER: Parse game date from session
# ===========================================================================
def parse_session_date(session, fallback_date):
    # API schema confirms gameDateLocal and gameDateUtc exist on session objects
    for field in ["gameDateLocal", "gameDateUtc"]:
        val = session.get(field, "")
        if val and isinstance(val, str):
            try:
                return datetime.fromisoformat(val.replace("Z", "").split("+")[0]).date()
            except:
                pass
    return fallback_date


# ===========================================================================
# AI CHATBOT FUNCTIONS
# ===========================================================================

def get_df_schema(df):
    """Return a compact schema description for the AI."""
    lines = []
    lines.append(f"DataFrame 'df' shape: {df.shape[0]:,} rows x {df.shape[1]} columns")
    lines.append(f"Date range: {df['GameDate'].min()} to {df['GameDate'].max()}")
    lines.append(f"Teams: {df['HomeTeam'].nunique()} unique home teams, {df['AwayTeam'].nunique()} unique away teams")
    lines.append(f"Pitchers: {df['Pitcher'].nunique()} unique (format: 'Last, First')")
    lines.append(f"Pitch types: {sorted(df['PitchType'].dropna().unique().tolist())}")
    lines.append("")
    lines.append("Columns and types:")
    for col in df.columns:
        lines.append(f"  {col}: {df[col].dtype} (sample: {df[col].dropna().iloc[0] if not df[col].dropna().empty else 'N/A'})")
    lines.append("")
    lines.append("Key column notes:")
    lines.append("  - Pitcher names are 'Last, First' format")
    lines.append("  - TopBottom: 'Top' = away team batting (home team pitching), 'Bottom' = home team batting (away team pitching)")
    lines.append("  - PitchCall values: StrikeSwinging, StrikeCalled, Ball, FoulBall, FoulBallNotFieldable, InPlay, HitByPitch")
    lines.append("  - KorBB values: Strikeout, Walk (blank otherwise)")
    lines.append("  - PlayResult values: Single, Double, Triple, HomeRun, Out, Error, FieldersChoice, Sacrifice (blank otherwise)")
    lines.append("  - SWING_CALLS = ['StrikeSwinging','FoulBall','FoulBallNotFieldable','InPlay']")
    lines.append("  - Whiff% = StrikeSwinging / swings * 100")
    lines.append("  - Chase% = swings on out-of-zone pitches / out-of-zone pitches * 100")
    lines.append("  - Zone: PlateLocHeight between 1.5-3.5, PlateLocSide between -0.83 and 0.83")
    lines.append("  - xwOBA column available for in-play events")
    lines.append("  - InZone column: True/False")
    return "\n".join(lines)


def run_ai_code(code_str, df):
    """Safely execute AI-generated pandas code and return result."""
    import io, traceback
    local_vars = {
        "df": df,
        "pd": pd,
        "np": np,
        "plt": plt,
        "result": None,
        "fig": None,
        "BG_COLOR": BG_COLOR,
        "PANEL_COLOR": PANEL_COLOR,
        "TEXT_COLOR": TEXT_COLOR,
        "ACCENT_COLOR": ACCENT_COLOR,
        "MUTED_TEXT": MUTED_TEXT,
        "GRID_COLOR": GRID_COLOR,
        "PITCH_COLORS": PITCH_COLORS,
        "pc": pc,
    }
    try:
        exec(compile(code_str, "<ai_code>", "exec"), local_vars)
        return local_vars.get("result"), local_vars.get("fig"), None
    except Exception as e:
        return None, None, traceback.format_exc()


def call_groq_api(messages, system_prompt):
    """Call the Groq API."""
    api_key = st.secrets.get("GROQ_API_KEY", "gsk_REPLACE_WITH_YOUR_GROQ_API_KEY")

    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}",
    }

    groq_messages = [{"role": "system", "content": system_prompt}] + messages

    payload = {
        "model": "llama-3.3-70b-versatile",
        "max_tokens": 2000,
        "messages": groq_messages,
        "temperature": 0.2,
    }
    try:
        resp = requests.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers=headers,
            json=payload,
            timeout=45,
        )
        if resp.status_code == 200:
            return resp.json()["choices"][0]["message"]["content"]
        else:
            return f"API error {resp.status_code}: {resp.text[:200]}"
    except Exception as e:
        return f"Request failed: {e}"

# ===========================================================================
# STREAMLIT UI
# ===========================================================================
st.title("⚾ TrackMan Pitching Report")

# ===========================================================================
# LOAD DATA FROM PARQUET
# ===========================================================================
df_all, parquet_path = load_all_pitches()

# ===========================================================================
# AI CHATBOT
# ===========================================================================
with st.expander("🤖 AI Baseball Analyst", expanded=False):
    st.markdown("Ask any question about pitching or hitting data. The AI has full access to all data in the parquet file.")

    if "chat_history" not in st.session_state:
        st.session_state["chat_history"] = []
    if "df_schema" not in st.session_state:
        st.session_state["df_schema"] = None

    if df_all is not None and st.session_state["df_schema"] is None:
        st.session_state["df_schema"] = get_df_schema(df_all)

    # Display chat history
    for msg in st.session_state["chat_history"]:
        with st.chat_message(msg["role"]):
            if msg.get("fig"):
                st.pyplot(msg["fig"])
            if msg.get("content"):
                st.markdown(msg["content"])

    user_input = st.chat_input("Ask about any pitcher, team, pitch type, hitting data...")
    if user_input and df_all is not None:
        st.session_state["chat_history"].append({"role": "user", "content": user_input})
        with st.chat_message("user"):
            st.markdown(user_input)

        schema = st.session_state["df_schema"]

        system_prompt = f"""You are an expert baseball data analyst. You have direct access to a pandas DataFrame called `df` containing college baseball TrackMan data.

DATAFRAME SCHEMA:
{schema}

YOUR JOB:
1. Write Python/pandas code to answer the user's question
2. Store the final answer in a variable called `result` (string)
3. Optionally create a matplotlib figure stored in `fig` for visual questions

ALWAYS respond in this exact format:
ANSWER: <1-2 sentence plain English answer here>
CODE:
```python
# your pandas code here
result = "your answer as a string"
fig = None  # or a matplotlib figure
```

RULES:
- Always set result to a readable string answer
- For charts, create fig using matplotlib. Style with: fig, ax = plt.subplots(figsize=(10,5), facecolor=BG_COLOR); ax.set_facecolor(PANEL_COLOR)
- Use pitch colors with pc(pitch_type) for pitch-specific charts
- Keep code simple and safe - no file I/O, no imports (pd, np, plt already available)
- For pitcher queries, names are 'Last, First' - use str.contains() for fuzzy matching
- For IP calculations: count outs recorded (KorBB=='Strikeout' or PlayResult in outs list) then divide by 3
- Whiff% = (PitchCall=='StrikeSwinging').sum() / PitchCall.isin(['StrikeSwinging','FoulBall','FoulBallNotFieldable','InPlay']).sum() * 100
- Zone% = InZone.sum() / len(s) * 100 (InZone column exists)"""

        messages = [
            {"role": m["role"], "content": m["content"]}
            for m in st.session_state["chat_history"]
            if m["role"] in ("user", "assistant") and m.get("content")
        ]

        with st.chat_message("assistant"):
            with st.spinner("Analyzing data..."):
                response = call_groq_api(messages, system_prompt)

            # Parse ANSWER and CODE blocks
            answer_text = ""
            fig = None
            result_text = ""

            if "ANSWER:" in response:
                answer_part = response.split("ANSWER:")[1]
                if "CODE:" in answer_part:
                    answer_text = answer_part.split("CODE:")[0].strip()
                    code_part = answer_part.split("CODE:")[1].strip()
                else:
                    answer_text = answer_part.strip()
                    code_part = ""
            else:
                answer_text = response
                code_part = ""

            # Extract code from markdown block
            if "```python" in code_part:
                code_str = code_part.split("```python")[1].split("```")[0].strip()
            elif "```" in code_part:
                code_str = code_part.split("```")[1].split("```")[0].strip()
            else:
                code_str = code_part.strip()

            # Run the code
            if code_str:
                result, fig, error = run_ai_code(code_str, df_all)
                if error:
                    st.markdown(answer_text)
                    st.caption(f"⚠️ Code execution note: {error[:200]}")
                else:
                    if fig:
                        st.pyplot(fig)
                    final_answer = str(result) if result else answer_text
                    st.markdown(final_answer)
            else:
                st.markdown(answer_text)

            st.session_state["chat_history"].append({
                "role": "assistant",
                "content": str(result) if (code_str and result) else answer_text,
                "fig": fig,
            })

    if st.session_state["chat_history"]:
        if st.button("🗑️ Clear chat", key="clear_chat"):
            st.session_state["chat_history"] = []
            st.rerun()

with st.sidebar:
    st.header("Report Settings")

    if df_all is None:
        st.error("❌ No data found. Run fetch_data.py first.")
        st.caption(f"Expected: {os.path.join(DATA_DIR, 'pitches.parquet')}")
        st.stop()

    last_updated = get_last_updated()
    st.success(f"✅ Data loaded\n\n{len(df_all):,} pitches · Updated {last_updated or 'unknown'}")

    # Date range filter
    all_dates = df_all["GameDate"].dropna()
    min_date = all_dates.min()
    max_date = all_dates.max()
    col1, col2 = st.columns(2)
    with col1:
        date_from = st.date_input("From", value=max_date - timedelta(days=7),
                                   min_value=min_date, max_value=max_date)
    with col2:
        date_to = st.date_input("To", value=max_date,
                                 min_value=min_date, max_value=max_date)

    if date_from > date_to:
        st.error("'From' date must be before 'To' date")
        st.stop()

    # Team picker
    teams_list = get_teams(df_all)
    if not teams_list:
        st.error("No teams found in data.")
        st.stop()

    prev_team = st.session_state.get("selected_team", None)
    default_idx = teams_list.index(prev_team) if prev_team and prev_team in teams_list else 0
    selected_team = st.selectbox("Select Team", teams_list, index=default_idx)
    st.session_state["selected_team"] = selected_team

    if st.button("🔄 Reset Selections", use_container_width=True):
        for k in ["pitcher_outings", "pitcher_names", "_team_key",
                  "_hm_loaded", "_pm_active_key", "_pm_pitchers"]:
            st.session_state.pop(k, None)
        st.rerun()

    st.divider()
    if D1_PCTLS:
        meta = D1_PCTLS.get("_meta", {})
        st.success(f"D1 Percentiles loaded\n\n{meta.get('sessions_scanned', 0)} sessions · {meta.get('generated', '?')[:10]}")
    else:
        st.warning("No D1_percentiles.json found.\nColor grading disabled.")

# ===========================================================================
# MAIN CONTENT
# ===========================================================================
team_name = st.session_state["selected_team"]
team_df = get_team_pitches(df_all, team_name, date_from, date_to)

if team_df.empty:
    st.warning(f"No pitches found for {team_name} between {date_from} and {date_to}")
    st.stop()

# Show games found
games = (team_df.groupby(["GameDate", "HomeTeam", "AwayTeam"])
         .size().reset_index().sort_values("GameDate"))
st.subheader(f"{team_name} — {len(games)} game(s)")
for _, row in games.iterrows():
    st.text(f"  📅 {row['GameDate']} — {row['HomeTeam']} vs {row['AwayTeam']}")

# Build pitcher list from parquet
cache_key = f"{team_name}_{date_from}_{date_to}"
if st.session_state.get("_team_key") != cache_key:
    pitcher_meta = {}
    for pn in sorted(team_df["Pitcher"].dropna().unique()):
        p_games = (team_df[team_df["Pitcher"] == pn]
                   .groupby(["GameDate", "HomeTeam", "AwayTeam"]))
        outings = []
        for (gdate, ht, at), _ in p_games:
            opp = at if team_name.lower() in ht.lower() else ht
            outings.append((gdate, opp))
        if outings:
            pitcher_meta[pn] = sorted(outings, key=lambda x: x[0])
    st.session_state["pitcher_meta_parquet"] = pitcher_meta
    st.session_state["pitcher_names"] = sorted(pitcher_meta.keys())
    st.session_state["_team_key"] = cache_key
    st.session_state.pop("pitcher_outings", None)

def load_full_pitcher_data(pitcher_names_to_load):
    """Build per-pitcher outing DataFrames from parquet — no API calls."""
    if "pitcher_outings" not in st.session_state:
        st.session_state["pitcher_outings"] = {}
    needed = [pn for pn in pitcher_names_to_load
              if pn not in st.session_state["pitcher_outings"]]
    if not needed:
        return
    for pn in needed:
        p_df_all = team_df[team_df["Pitcher"] == pn].copy()
        p_df_all = p_df_all.sort_values(["GameDate", "PitchNo"]).reset_index(drop=True)
        p_df_all["PitchType"] = p_df_all.apply(resolve_pt, axis=1)
        p_df_all, _ = auto_correct_pitch_types(p_df_all)
        p_df_all["xwOBA"] = p_df_all.apply(
            lambda r: calc_xwoba(r["ExitSpeed"], r["LaunchAngle"])
            if r["PitchCall"] == "InPlay" else np.nan, axis=1)
        p_df_all["InZone"] = in_zone(p_df_all)
        outings = []
        for gdate, g_df in p_df_all.groupby("GameDate"):
            ht = g_df["HomeTeam"].iloc[0] if "HomeTeam" in g_df.columns else ""
            at = g_df["AwayTeam"].iloc[0] if "AwayTeam" in g_df.columns else ""
            opp = at if team_name.lower() in ht.lower() else ht
            outings.append((g_df.reset_index(drop=True), gdate, opp))
        st.session_state["pitcher_outings"][pn] = sorted(outings, key=lambda x: x[1])

if "pitcher_names" in st.session_state and st.session_state["pitcher_names"]:
    st.divider()
    pitcher_meta = st.session_state.get("pitcher_meta_parquet", {})
    outing_labels = []
    for pn in st.session_state["pitcher_names"]:
        outings = pitcher_meta.get(pn, [])
        if len(outings) > 1:
            outing_labels.append(f"{pn}  ({len(outings)} outings)")
        elif outings:
            gd, op = outings[0]
            outing_labels.append(f"{pn}  ({gd} vs {op})")
        else:
            outing_labels.append(pn)

    selected_labels = st.multiselect("Select Pitcher(s)", outing_labels, default=None)
    label_to_name = dict(zip(outing_labels, st.session_state["pitcher_names"]))
    selected_names = [label_to_name[lbl] for lbl in selected_labels]

    if selected_names:
        tab_reports, tab_summary, tab_heatmaps, tab_debug = st.tabs(
            ["📄 Game Reports", "📊 Season Summary", "🔥 Heatmaps", "🔧 Debug"])

        # ========== TAB 1: GAME REPORTS ==========
        with tab_reports:
            if st.button("⚾ Generate Game Reports", type="primary",
                         use_container_width=True, key="btn_reports"):
                figures = []
                with st.spinner("Generating reports..."):
                    load_full_pitcher_data(selected_names)
                    for pname in selected_names:
                        if pname not in st.session_state.get("pitcher_outings", {}):
                            continue
                        for p_data, gdate, opp in st.session_state["pitcher_outings"][pname]:
                            if len(p_data) == 0:
                                continue
                            fig = generate_pitcher_page(p_data, pname, gdate, opp)
                            if fig:
                                figures.append((f"{pname} ({gdate} vs {opp})", fig))
                if figures:
                    for label, fig in figures:
                        st.pyplot(fig, use_container_width=True)
                        st.divider()
                    pdf_buffer = io.BytesIO()
                    with PdfPages(pdf_buffer) as pdf:
                        for label, fig in figures:
                            pdf.savefig(fig, bbox_inches="tight", facecolor=BG_COLOR)
                            plt.close(fig)
                    pdf_buffer.seek(0)
                    safe_team = team_name.replace(" ", "")[:15]
                    st.download_button("📥 Download Game Reports PDF", data=pdf_buffer,
                                       file_name=f"GameReports_{safe_team}_{date_from}_to_{date_to}.pdf",
                                       mime="application/pdf", type="primary",
                                       use_container_width=True)
                else:
                    st.error("No reports generated")

        # ========== TAB 2: SEASON SUMMARY ==========
        with tab_summary:
            if st.button("📊 Generate Season Summaries", type="primary",
                         use_container_width=True, key="btn_summary"):
                figures = []
                with st.spinner("Building season summaries from local data..."):
                    season_df = get_team_pitches(
                        df_all, team_name,
                        df_all["GameDate"].min(), df_all["GameDate"].max())
                    for pname in selected_names:
                        p_season = season_df[season_df["Pitcher"] == pname].copy()
                        if p_season.empty:
                            st.warning(f"No season data for {pname}")
                            continue
                        p_season["PitchType"] = p_season.apply(resolve_pt, axis=1)
                        p_season, _ = auto_correct_pitch_types(p_season)
                        p_season["xwOBA"] = p_season.apply(
                            lambda r: calc_xwoba(r["ExitSpeed"], r["LaunchAngle"])
                            if r["PitchCall"] == "InPlay" else np.nan, axis=1)
                        p_season["InZone"] = in_zone(p_season)
                        outings = []
                        for gdate, g_df in p_season.groupby("GameDate"):
                            ht = g_df["HomeTeam"].iloc[0] if "HomeTeam" in g_df.columns else ""
                            at = g_df["AwayTeam"].iloc[0] if "AwayTeam" in g_df.columns else ""
                            opp = at if team_name.lower() in ht.lower() else ht
                            outings.append((g_df.reset_index(drop=True), gdate, opp))
                        outings = sorted(outings, key=lambda x: x[1])
                        fig = generate_season_summary(
                            pname, outings,
                            df_all["GameDate"].min(), df_all["GameDate"].max())
                        if fig:
                            figures.append((pname, fig))
                if figures:
                    for label, fig in figures:
                        st.pyplot(fig, use_container_width=True)
                        st.divider()
                    pdf_buffer = io.BytesIO()
                    with PdfPages(pdf_buffer) as pdf:
                        for label, fig in figures:
                            pdf.savefig(fig, bbox_inches="tight", facecolor=BG_COLOR)
                            plt.close(fig)
                    pdf_buffer.seek(0)
                    safe_team = team_name.replace(" ", "")[:15]
                    st.download_button("📥 Download Season Summary PDF", data=pdf_buffer,
                                       file_name=f"SeasonSummary_{safe_team}_2026.pdf",
                                       mime="application/pdf", type="primary",
                                       use_container_width=True)
                else:
                    st.error("No summaries generated")

        # ========== TAB 3: HEATMAPS ==========
        with tab_heatmaps:
            hm_pitcher = (selected_names[0] if len(selected_names) == 1
                          else st.selectbox("Select pitcher for heatmaps",
                                            selected_names, key="hm_pitcher"))
            if st.button("📂 Load Pitch Data", type="primary",
                         use_container_width=True, key="btn_load_hm"):
                load_full_pitcher_data([hm_pitcher])
                st.session_state["_hm_loaded"] = hm_pitcher

            if (st.session_state.get("_hm_loaded") == hm_pitcher and
                    hm_pitcher in st.session_state.get("pitcher_outings", {})):
                all_outing_dfs = [p_df for p_df, _, _
                                  in st.session_state["pitcher_outings"][hm_pitcher]]
                hm_data = (pd.concat(all_outing_dfs, ignore_index=True)
                           if all_outing_dfs else pd.DataFrame())
                if not hm_data.empty:
                    avail_types = hm_data["PitchType"].value_counts()
                    avail_types = avail_types[avail_types >= 5].index.tolist()
                    if avail_types:
                        hm_pitch_type = st.selectbox("Select Pitch Type", avail_types,
                                                      key="hm_pt_select")
                        hm_metric = st.selectbox(
                            "Select Metric",
                            ["Location", "Run Value", "Whiff Rate", "xwOBA"],
                            key="hm_metric_select")
                        metric_map = {"Location": "location", "Run Value": "run_value",
                                      "Whiff Rate": "whiff", "xwOBA": "xwoba"}
                        if st.button("🔥 Generate Heatmap", type="primary",
                                     use_container_width=True, key="btn_gen_hm"):
                            with st.spinner(f"Generating {hm_metric} heatmap..."):
                                fig = generate_heatmap(hm_data, hm_pitch_type,
                                                       metric_map[hm_metric])
                            if fig:
                                buf = io.BytesIO()
                                fig.savefig(buf, format="png", bbox_inches="tight",
                                            dpi=150, facecolor=BG_COLOR)
                                buf.seek(0)
                                st.session_state["_hm_fig_bytes"] = buf.getvalue()
                                st.session_state["_hm_fig_label"] = (
                                    f"{hm_metric}_{hm_pitcher}_{hm_pitch_type}")
                                st.pyplot(fig, use_container_width=True)
                                plt.close(fig)
                            else:
                                st.warning(f"Not enough {hm_pitch_type} data for heatmap")
                        if st.session_state.get("_hm_fig_bytes"):
                            st.download_button(
                                "📥 Download Heatmap",
                                data=st.session_state["_hm_fig_bytes"],
                                file_name=f"Heatmap_{st.session_state.get('_hm_fig_label','heatmap')}.png",
                                mime="image/png", use_container_width=True)
                    else:
                        st.warning("No pitch types with enough data (need 5+)")
                else:
                    st.warning("No pitch data available")
            elif (st.session_state.get("_hm_loaded") and
                  st.session_state.get("_hm_loaded") != hm_pitcher):
                st.info("Click **Load Pitch Data** to load data for this pitcher")

        # ========== TAB 4: DEBUG ==========
        with tab_debug:
            st.caption("Raw PA-level data for verifying IP/ER calculations.")
            if st.button("🔧 Load & Show Debug Data", type="primary",
                         use_container_width=True, key="btn_debug"):
                load_full_pitcher_data(selected_names)
                for pname in selected_names:
                    if pname not in st.session_state.get("pitcher_outings", {}):
                        st.warning(f"No data for {pname}")
                        continue
                    st.subheader(f"🔍 {pname}")
                    for p_df, gdate, opp in st.session_state["pitcher_outings"][pname]:
                        st.write(f"**{gdate} vs {opp}** — {len(p_df)} pitches")
                        pa_rows = []
                        debug_outs = 0
                        reached_results = ("Single", "Double", "Triple", "HomeRun",
                                           "Error", "FieldersChoice", "CaughtStealing",
                                           "ReachedOnError")
                        for (inn, pa_num), grp in p_df.groupby(["Inning", "PAofInning"]):
                            last = grp.loc[grp["PitchNo"].idxmax()]
                            oop = last.get("OutsOnPlay", "")
                            korbb = last.get("KorBB", "")
                            result = last.get("PlayResult", "")
                            out_src = ""
                            if pd.notna(oop) and float(oop) > 0:
                                debug_outs += int(float(oop))
                                out_src = f"+{int(float(oop))} (OutsOnPlay)"
                            elif korbb == "Strikeout":
                                if result in reached_results:
                                    out_src = f"K but reached ({result}) → NO out"
                                else:
                                    debug_outs += 1
                                    out_src = "+1 (K)"
                            pa_rows.append({
                                "Inn": inn, "PA#": pa_num, "#P": len(grp),
                                "Batter": last.get("Batter", ""),
                                "LastCall": last.get("PitchCall", ""),
                                "KorBB": korbb, "PlayResult": result,
                                "OutsOnPlay": oop, "RunsScored": last.get("RunsScored", ""),
                                "OutCredit": out_src,
                            })
                        pa_table = pd.DataFrame(pa_rows)
                        st.dataframe(pa_table, use_container_width=True, hide_index=True)
                        ip_s = calc_ip(p_df)
                        er_s = calc_er(p_df)
                        pa_s = calc_pa(p_df)
                        k_s = int((p_df["KorBB"] == "Strikeout").sum())
                        bb_s = int((p_df["KorBB"] == "Walk").sum())
                        st.write(f"**Computed:** IP={ip_s}, ER={er_s}, PA={pa_s}, "
                                 f"K={k_s}, BB={bb_s}, Debug outs={debug_outs}")
                        st.write("**Raw OutsOnPlay:**",
                                 p_df["OutsOnPlay"].value_counts().to_dict())
                        st.write("**Raw RunsScored:**",
                                 p_df["RunsScored"].value_counts().to_dict())
                        st.divider()

st.divider()
st.title("🎯 Pitch Mix Analysis")

if "selected_team" in st.session_state:
    pm_team = st.session_state["selected_team"]

    pm_col1, pm_col2 = st.columns(2)
    with pm_col1:
        pm_from = st.date_input("From", value=date(2026, 1, 1), key="pm_from")
    with pm_col2:
        pm_to = st.date_input("To", value=date.today(), key="pm_to")

    pm_cache_key = f"_pm_data_{pm_team}_{pm_from}_{pm_to}"

    if st.button("📂 Load Pitchers", type="secondary", use_container_width=True, key="btn_pm_load"):
        with st.spinner("Loading pitch mix data..."):
            pm_df = get_team_pitches(df_all, pm_team, pm_from, pm_to)
            pm_all_outings = {}
            if not pm_df.empty:
                pm_df = pm_df.copy()
                pm_df["PitchType"] = pm_df.apply(resolve_pt, axis=1)
                pm_df, _ = auto_correct_pitch_types(pm_df)
                pm_df["InZone"] = in_zone(pm_df)
                for pn in pm_df["Pitcher"].dropna().unique():
                    p_all = pm_df[pm_df["Pitcher"] == pn]
                    for gdate, g_df in p_all.groupby("GameDate"):
                        ht = g_df["HomeTeam"].iloc[0] if "HomeTeam" in g_df.columns else ""
                        at = g_df["AwayTeam"].iloc[0] if "AwayTeam" in g_df.columns else ""
                        opp = at if pm_team.lower() in ht.lower() else ht
                        p_df = g_df.sort_values("PitchNo").reset_index(drop=True)
                        if pn not in pm_all_outings:
                            pm_all_outings[pn] = []
                        pm_all_outings[pn].append((p_df, gdate, opp))
            st.session_state[pm_cache_key] = pm_all_outings
            st.session_state["_pm_pitchers"] = sorted(pm_all_outings.keys())
            st.session_state["_pm_active_key"] = pm_cache_key

    if st.session_state.get("_pm_active_key") == pm_cache_key and "_pm_pitchers" in st.session_state:
        pm_outings = st.session_state.get(pm_cache_key, {})

        if not st.session_state["_pm_pitchers"]:
            st.warning("No pitchers found")
        else:
            pm_pitcher = st.selectbox("Select Pitcher", st.session_state["_pm_pitchers"], key="pm_pitcher")
            fc1, fc2 = st.columns(2)
            with fc1:
                pm_hand = st.selectbox("Batter Hand", ["All", "vs RHH", "vs LHH"], key="pm_hand")
            with fc2:
                pm_tto = st.selectbox("Time Through Order",
                                      ["All", "1st Time", "2nd Time", "3rd Time", "4th+ Time"], key="pm_tto")

            if st.button("🎯 Generate Pitch Mix", type="primary", use_container_width=True, key="btn_pitchmix"):
                if pm_pitcher not in pm_outings or not pm_outings[pm_pitcher]:
                    st.warning(f"No data found for {pm_pitcher}")
                else:
                    all_dfs = []
                    for p_df, gdate, opp in pm_outings[pm_pitcher]:
                        df_copy = p_df.copy()
                        df_copy["_game_date"] = gdate
                        df_copy["_opp"] = opp
                        all_dfs.append(df_copy)
                    pitch_data = pd.concat(all_dfs, ignore_index=True)

                    pitch_data["_TTO"] = 0
                    for gd in pitch_data["_game_date"].unique():
                        game_mask = pitch_data["_game_date"] == gd
                        game_df = pitch_data[game_mask].copy()
                        pa_order = game_df.groupby(["Inning", "PAofInning"]).first().reset_index()
                        pa_order = pa_order.sort_values("PitchNo")
                        batter_count = {}
                        pa_tto = {}
                        for _, pa_row in pa_order.iterrows():
                            batter = pa_row["Batter"]
                            if batter not in batter_count:
                                batter_count[batter] = 0
                            batter_count[batter] += 1
                            pa_key = (pa_row["Inning"], pa_row["PAofInning"])
                            pa_tto[pa_key] = batter_count[batter]
                        for idx in pitch_data[game_mask].index:
                            row = pitch_data.loc[idx]
                            pa_key = (row["Inning"], row["PAofInning"])
                            pitch_data.loc[idx, "_TTO"] = pa_tto.get(pa_key, 1)

                    filtered = pitch_data.copy()
                    if pm_hand == "vs RHH":
                        filtered = filtered[filtered["BatterSide"] == "Right"]
                    elif pm_hand == "vs LHH":
                        filtered = filtered[filtered["BatterSide"] == "Left"]
                    if pm_tto == "1st Time":
                        filtered = filtered[filtered["_TTO"] == 1]
                    elif pm_tto == "2nd Time":
                        filtered = filtered[filtered["_TTO"] == 2]
                    elif pm_tto == "3rd Time":
                        filtered = filtered[filtered["_TTO"] == 3]
                    elif pm_tto == "4th+ Time":
                        filtered = filtered[filtered["_TTO"] >= 4]

                    if len(filtered) == 0:
                        st.warning("No pitches match these filters")
                    else:
                        N = len(filtered)
                        pts = filtered["PitchType"].value_counts().index.tolist()

                        def get_count_cat(balls, strikes):
                            cats = []
                            if (balls, strikes) in [(0, 0), (1, 0), (0, 1)]:
                                cats.append("early")
                            if strikes > balls and strikes >= 1:
                                cats.append("ahead")
                            if balls > strikes:
                                cats.append("behind")
                            if strikes < 2:
                                cats.append("pre2k")
                            if strikes == 2:
                                cats.append("twok")
                            return cats

                        filtered["_count_cats"] = filtered.apply(
                            lambda r: get_count_cat(
                                int(r["Balls"]) if pd.notna(r["Balls"]) else 0,
                                int(r["Strikes"]) if pd.notna(r["Strikes"]) else 0
                            ), axis=1)

                        situations = {
                            "All Counts": filtered,
                            "Early Count": filtered[filtered["_count_cats"].apply(lambda x: "early" in x)],
                            "Pitcher Ahead": filtered[filtered["_count_cats"].apply(lambda x: "ahead" in x)],
                            "Pitcher Behind": filtered[filtered["_count_cats"].apply(lambda x: "behind" in x)],
                            "Pre Two Strikes": filtered[filtered["_count_cats"].apply(lambda x: "pre2k" in x)],
                            "Two Strikes": filtered[filtered["_count_cats"].apply(lambda x: "twok" in x)],
                        }

                        table_data = []
                        all_counts_pcts = {}
                        for pt in pts:
                            all_pct = len(filtered[filtered["PitchType"] == pt]) / N * 100 if N > 0 else 0
                            all_counts_pcts[pt] = all_pct

                        for pt in pts:
                            row_d = {"Pitch Type": pt}
                            for sit_name, sit_df in situations.items():
                                sit_n = len(sit_df)
                                pct = len(sit_df[sit_df["PitchType"] == pt]) / sit_n * 100 if sit_n > 0 else 0
                                row_d[sit_name] = pct
                            table_data.append(row_d)

                        hand_label = pm_hand if pm_hand != "All" else "vs All"
                        tto_label = pm_tto if pm_tto != "All" else "All ABs"
                        st.markdown(f"### {pm_pitcher}")
                        st.caption(f"Pitch Mix {hand_label} · {tto_label} · {pm_from} to {pm_to} · {N} pitches")

                        fig, ax = plt.subplots(figsize=(14, max(2.5, 0.6 * len(pts) + 1.2)),
                                               facecolor="#1a1d23")
                        ax.axis("off")
                        col_labels = list(situations.keys())
                        cell_text = []
                        for rd in table_data:
                            cell_text.append([f"{rd[c]:.0f}%" for c in col_labels])

                        tbl = ax.table(
                            cellText=cell_text,
                            rowLabels=[r["Pitch Type"] for r in table_data],
                            colLabels=[c.upper().replace(" ", "\n") for c in col_labels],
                            loc="center", cellLoc="center"
                        )
                        tbl.auto_set_font_size(False)
                        tbl.set_fontsize(10)
                        tbl.scale(1, 2.0)

                        for (row, col), cell in tbl.get_celld().items():
                            cell.set_edgecolor("#2a2d35")
                            cell.set_linewidth(0.5)
                            if row == 0:
                                cell.set_facecolor("#2a2d35")
                                cell.set_text_props(fontweight="bold", color="#8890a0",
                                                    fontfamily="monospace", fontsize=8)
                            elif col == -1:
                                pt_name = cell.get_text().get_text()
                                cell.set_facecolor("#1a1d23")
                                cell.get_text().set_text(f"● {pt_name}")
                                cell.get_text().set_color(pc(pt_name))
                                cell.set_text_props(fontweight="bold", fontfamily="monospace", fontsize=10)
                            else:
                                cell.set_facecolor("#1e2128")
                                pt_name = table_data[row - 1]["Pitch Type"]
                                col_name = col_labels[col]
                                val = table_data[row - 1][col_name]
                                base = all_counts_pcts.get(pt_name, 0)
                                diff = val - base
                                if col_name != "All Counts" and abs(diff) >= 5:
                                    if diff >= 5:
                                        cell.set_facecolor("#1a3a2a")
                                        cell.set_text_props(color="#4ade80", fontweight="bold",
                                                            fontfamily="monospace", fontsize=10)
                                    else:
                                        cell.set_facecolor("#3a1a1a")
                                        cell.set_text_props(color="#f87171", fontweight="bold",
                                                            fontfamily="monospace", fontsize=10)
                                else:
                                    cell.set_text_props(color="white", fontfamily="monospace", fontsize=10)

                        fig.tight_layout()
                        st.pyplot(fig, use_container_width=True)

                        buf = io.BytesIO()
                        fig.savefig(buf, format="png", bbox_inches="tight", dpi=150, facecolor="#1a1d23")
                        buf.seek(0)
                        st.download_button("📥 Download Pitch Mix", data=buf,
                                           file_name=f"PitchMix_{pm_pitcher}_{pm_hand}_{pm_tto}.png",
                                           mime="image/png", use_container_width=True)
                        plt.close(fig)

                        with st.expander("📋 Sample sizes per situation"):
                            size_data = {name: len(sdf) for name, sdf in situations.items()}
                            st.write(size_data)
else:
    st.info("Select a team above to use Pitch Mix")
